name: Build Images

on:
  push:
    branches:
      - initial-setup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Container
        run: |
          docker buildx build \
          --build-arg PYTHON_VERSION=3.12 \
          --build-arg TF_VERSION=1.5.7 \
          --platform linux/amd64,linux/arm64 \
          .
