name: Build Images

on:
  push:
    branches:
      - initial-setup

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_version:
          - "1.7.5"
          - "1.6.6"
          - "1.5.7"
        python_version:
          - "3.12"
#          - "3.11"
#          - "3.10"
#          - "3.9"
#          - "3.8"
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        run: |
          docker buildx build \
          --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
          --build-arg TF_VERSION=${{ matrix.tf_version }} \
          --platform linux/amd64,linux/arm64 \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE}}:${{ matrix.tf_version }}-py${{ matrix.python_version }} \
          --push \
          .
